In [73]:
import pandas as pd

dataframe: pd.DataFrame = pd.read_csv("./titanic.csv")

dataframe

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [74]:
dataframe[(dataframe["Age"]>20.0)&(dataframe["Age"]<40.0)][["Name", "Fare"]]

                                                  Name     Fare
0                              Braund, Mr. Owen Harris   7.2500
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  71.2833
2                               Heikkinen, Miss. Laina   7.9250
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  53.1000
4                             Allen, Mr. William Henry   8.0500
..                                                 ...      ...
884                             Sutehall, Mr. Henry Jr   7.0500
885               Rice, Mrs. William (Margaret Norton)  29.1250
886                              Montvila, Rev. Juozas  13.0000
889                              Behr, Mr. Karl Howell  30.0000
890                                Dooley, Mr. Patrick   7.7500

[372 rows x 2 columns]

In [75]:
dataframe[dataframe["Fare"]>100.0][["PassengerId", "Name", "Pclass"]]

     PassengerId                                               Name  Pclass
27            28                     Fortune, Mr. Charles Alexander       1
31            32     Spencer, Mrs. William Augustus (Marie Eugenie)       1
88            89                         Fortune, Miss. Mabel Helen       1
118          119                           Baxter, Mr. Quigg Edmond       1
195          196                               Lurette, Miss. Elise       1
215          216                            Newell, Miss. Madeleine       1
258          259                                   Ward, Miss. Anna       1
268          269      Graham, Mrs. William Thompson (Edith Junkins)       1
269          270                             Bissette, Miss. Amelia       1
297          298                       Allison, Miss. Helen Loraine       1
299          300    Baxter, Mrs. James (Helene DeLaudeniere Chaput)       1
305          306                     Allison, Master. Hudson Trevor       1
306          307                            Fleming, Miss. Margaret       1
307          308  Penasco y Castellana, Mrs. Victor de Satode (M...       1
311          312                         Ryerson, Miss. Emily Borie       1
318          319                           Wick, Miss. Mary Natalie       1
319          320  Spedden, Mrs. Frederic Oakley (Margaretta Corn...       1
325          326                           Young, Miss. Marie Grice       1
332          333                          Graham, Mr. George Edward       1
334          335  Frauenthal, Mrs. Henry William (Clara Heinshei...       1
337          338                    Burns, Miss. Elizabeth Margaret       1
341          342                     Fortune, Miss. Alice Elizabeth       1
373          374                                Ringhini, Mr. Sante       1
377          378                          Widener, Mr. Harry Elkins       1
380          381                              Bidois, Miss. Rosalie       1
390          391                         Carter, Mr. William Ernest       1
393          394                             Newell, Miss. Marjorie       1
435          436                          Carter, Miss. Lucile Polk       1
438          439                                  Fortune, Mr. Mark       1
498          499    Allison, Mrs. Hudson J C (Bessie Waldo Daniels)       1
505          506         Penasco y Castellana, Mr. Victor de Satode       1
527          528                                 Farthing, Mr. John       1
537          538                                LeRoy, Miss. Bertha       1
544          545                         Douglas, Mr. Walter Donald       1
550          551                        Thayer, Mr. John Borland Jr       1
557          558                                Robbins, Mr. Victor       1
581          582  Thayer, Mrs. John Borland (Marian Longstreth M...       1
609          610                          Shutes, Miss. Elizabeth W       1
659          660                         Newell, Mr. Arthur Webster       1
660          661                      Frauenthal, Dr. Henry William       1
679          680                 Cardeza, Mr. Thomas Drake Martinez       1
689          690                  Madill, Miss. Georgette Alexandra       1
698          699                           Thayer, Mr. John Borland       1
700          701  Astor, Mrs. John Jacob (Madeleine Talmadge Force)       1
708          709                               Cleaver, Miss. Alice       1
716          717                      Endres, Miss. Caroline Louise       1
730          731                      Allen, Miss. Elisabeth Walton       1
737          738                             Lesurer, Mr. Gustave J       1
742          743              Ryerson, Miss. Susan Parker "Suzette"       1
763          764          Carter, Mrs. William Ernest (Lucile Polk)       1
779          780  Robert, Mrs. Edward Scott (Elisabeth Walton Mc...       1
802          803                Carter, Master. William Thornton II       1
856          857         Wick, Mrs. George Dennick (Mary Hitchcock)       1

In [76]:
dataframe[(dataframe["Survived"]==1)&(dataframe["Pclass"]==3)]["Name"]

2                                 Heikkinen, Miss. Laina
8      Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)
10                       Sandstrom, Miss. Marguerite Rut
19                               Masselmani, Mrs. Fatima
22                           McGowan, Miss. Anna "Annie"
                             ...
838                                      Chip, Mr. Chang
855                           Aks, Mrs. Sam (Leah Rosen)
858                Baclini, Mrs. Solomon (Latifa Qurban)
869                      Johnson, Master. Harold Theodor
875                     Najib, Miss. Adele Kiamie "Jane"
Name: Name, Length: 119, dtype: str

In [77]:
dataframe.loc[:5, "Name"] = "Test Passenger"
dataframe

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,Test Passenger,male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,Test Passenger,female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,Test Passenger,female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,Test Passenger,female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,Test Passenger,male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [78]:
dataframe.iloc[10:20, 1:6]

,Survived,Pclass,Name,Sex,Age
10,1,3,"Sandstrom, Miss. Marguerite Rut",female,4.0
11,1,1,"Bonnell, Miss. Elizabeth",female,58.0
12,0,3,"Saundercock, Mr. William Henry",male,20.0
13,0,3,"Andersson, Mr. Anders Johan",male,39.0
14,0,3,"Vestrom, Miss. Hulda Amanda Adolfina",female,14.0
15,1,2,"Hewlett, Mrs. (Mary D Kingcome)",female,55.0
16,0,3,"Rice, Master. Eugene",male,2.0
17,1,2,"Williams, Mr. Charles Eugene",male,NaN
18,0,3,"Vander Planke, Mrs. Julius (Emelia Maria Vande...",female,31.0
19,1,3,"Masselmani, Mrs. Fatima",female,NaN

In [79]:
dataframe.loc[10:16, "Fare"] = 999
dataframe[10:16]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
10,11,1,3,"Sandstrom, Miss. Marguerite Rut",female,4.0,1,1,PP 9549,999.0,G6,S
11,12,1,1,"Bonnell, Miss. Elizabeth",female,58.0,0,0,113783,999.0,C103,S
12,13,0,3,"Saundercock, Mr. William Henry",male,20.0,0,0,A/5. 2151,999.0,NaN,S
13,14,0,3,"Andersson, Mr. Anders Johan",male,39.0,1,5,347082,999.0,NaN,S
14,15,0,3,"Vestrom, Miss. Hulda Amanda Adolfina",female,14.0,0,0,350406,999.0,NaN,S
15,16,1,2,"Hewlett, Mrs. (Mary D Kingcome)",female,55.0,0,0,248706,999.0,NaN,S

In [80]:
dataframe["FarePerPerson"] = dataframe["Fare"] / (dataframe["SibSp"] + 1)
dataframe

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,FarePerPerson
0,1,0,3,Test Passenger,male,22.0,1,0,A/5 21171,7.2500,NaN,S,3.62500
1,2,1,1,Test Passenger,female,38.0,1,0,PC 17599,71.2833,C85,C,35.64165
2,3,1,3,Test Passenger,female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,7.92500
3,4,1,1,Test Passenger,female,35.0,1,0,113803,53.1000,C123,S,26.55000
4,5,0,3,Test Passenger,male,35.0,0,0,373450,8.0500,NaN,S,8.05000
...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S,13.00000
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S,30.00000
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S,11.72500
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C,30.00000
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q,7.75000

In [81]:
def get_age_group(age: float) -> str:
  if age < 12: return "Child"
  elif 12 <= age <= 18: return "Teen"
  else: return "Adult"

dataframe["AgeGroup"] = dataframe["Age"].apply(get_age_group)

dataframe

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,FarePerPerson,AgeGroup
0,1,0,3,Test Passenger,male,22.0,1,0,A/5 21171,7.2500,NaN,S,3.62500,Adult
1,2,1,1,Test Passenger,female,38.0,1,0,PC 17599,71.2833,C85,C,35.64165,Adult
2,3,1,3,Test Passenger,female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,7.92500,Adult
3,4,1,1,Test Passenger,female,35.0,1,0,113803,53.1000,C123,S,26.55000,Adult
4,5,0,3,Test Passenger,male,35.0,0,0,373450,8.0500,NaN,S,8.05000,Adult
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S,13.00000,Adult
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S,30.00000,Adult
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S,11.72500,Adult
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C,30.00000,Adult
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q,7.75000,Adult

In [82]:
# print(
#   len(dataframe[dataframe["AgeGroup"]=="Child"]),
#   len(dataframe[dataframe["AgeGroup"]=="Teen"]),
#   len(dataframe[dataframe["AgeGroup"]=="Adult"])
# )

dataframe["AgeGroup"].value_counts()

AgeGroup
Adult    752
Teen      71
Child     68
Name: count, dtype: int64

In [83]:
len(dataframe[dataframe["Age"] > 60.0])

22

In [84]:
[dataframe[dataframe["Pclass"]==i]["Age"].mean() for i in range(1, 4)]

[np.float64(38.233440860215055),
 np.float64(29.87763005780347),
 np.float64(25.14061971830986)]

In [85]:
max(dataframe[dataframe["Survived"]==1]["Fare"])

999.0

In [86]:
def get_fare_category(fare: float) -> "str":
  if fare < 20.0: return "Low"
  elif 20.0 <= fare <= 50.0: return "Medium"
  else: return "High"

dataframe["FareCategory"] = dataframe["Fare"].apply(get_fare_category)

dataframe["FareCategory"].value_counts()

FareCategory
Low       511
Medium    213
High      167
Name: count, dtype: int64

In [87]:
dataframe[(dataframe["Sex"]=="female")&(dataframe["Pclass"]==1)&(dataframe["Age"]>50.0)]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,FarePerPerson,AgeGroup,FareCategory
11,12,1,1,"Bonnell, Miss. Elizabeth",female,58.0,0,0,113783,999.0000,C103,S,999.000000,Adult,High
195,196,1,1,"Lurette, Miss. Elise",female,58.0,0,0,PC 17569,146.5208,B80,C,146.520800,Adult,High
268,269,1,1,"Graham, Mrs. William Thompson (Edith Junkins)",female,58.0,0,1,PC 17582,153.4625,C125,S,153.462500,Adult,High
275,276,1,1,"Andrews, Miss. Kornelia Theodosia",female,63.0,1,0,13502,77.9583,D7,S,38.979150,Adult,High
366,367,1,1,"Warren, Mrs. Frank Manley (Anna Sophia Atkinson)",female,60.0,1,0,110813,75.2500,D37,C,37.625000,Adult,High
496,497,1,1,"Eustis, Miss. Elizabeth Mussey",female,54.0,1,0,36947,78.2667,D20,C,39.133350,Adult,High
513,514,1,1,"Rothschild, Mrs. Martin (Elizabeth L. Barrett)",female,54.0,1,0,PC 17603,59.4000,NaN,C,29.700000,Adult,High
571,572,1,1,"Appleton, Mrs. Edward Dale (Charlotte Lamson)",female,53.0,2,0,11769,51.4792,C101,S,17.159733,Adult,High
591,592,1,1,"Stephenson, Mrs. Walter Bertram (Martha Eustis)",female,52.0,1,0,36947,78.2667,D20,C,39.133350,Adult,High
765,766,1,1,"Hogeboom, Mrs. John C (Anna Andrews)",female,51.0,1,0,13502,77.9583,D11,S,38.979150,Adult,High
820,821,1,1,"Hays, Mrs. Charles Melville (Clara Jennings Gr...",female,52.0,1,1,12749,93.5000,B69,S,46.750000,Adult,High
829,830,1,1,"Stone, Mrs. George Nelson (Martha Evelyn)",female,62.0,0,0,113572,80.0000,B28,NaN,80.000000,Adult,High
879,880,1,1,"Potter, Mrs. Thomas Jr (Lily Alexenia Wilson)",female,56.0,0,1,11767,83.1583,C50,C,83.158300,Adult,High

In [88]:
dataframe["Sex"] = dataframe["Sex"].replace({"male": "M", "female": "F"})

dataframe.rename(columns={"Sex": "Gender"}, inplace=True)

dataframe

,PassengerId,Survived,Pclass,Name,Gender,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,FarePerPerson,AgeGroup,FareCategory
0,1,0,3,Test Passenger,M,22.0,1,0,A/5 21171,7.2500,NaN,S,3.62500,Adult,Low
1,2,1,1,Test Passenger,F,38.0,1,0,PC 17599,71.2833,C85,C,35.64165,Adult,High
2,3,1,3,Test Passenger,F,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,7.92500,Adult,Low
3,4,1,1,Test Passenger,F,35.0,1,0,113803,53.1000,C123,S,26.55000,Adult,High
4,5,0,3,Test Passenger,M,35.0,0,0,373450,8.0500,NaN,S,8.05000,Adult,Low
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",M,27.0,0,0,211536,13.0000,NaN,S,13.00000,Adult,Low
887,888,1,1,"Graham, Miss. Margaret Edith",F,19.0,0,0,112053,30.0000,B42,S,30.00000,Adult,Medium
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",F,NaN,1,2,W./C. 6607,23.4500,NaN,S,11.72500,Adult,Medium
889,890,1,1,"Behr, Mr. Karl Howell",M,26.0,0,0,111369,30.0000,C148,C,30.00000,Adult,Medium
890,891,0,3,"Dooley, Mr. Patrick",M,32.0,0,0,370376,7.7500,NaN,Q,7.75000,Adult,Low

In [95]:
# dataframe.sort_values("PassengerId", ascending=False)

# dataframe.sort_values("PassengerId")[::-1]

dataframe.sort_values(["Age", "Fare"])

,PassengerId,Survived,Pclass,Name,Gender,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,FarePerPerson,AgeGroup,FareCategory
803,804,1,3,"Thomas, Master. Assad Alexander",M,0.42,0,1,2625,8.5167,NaN,C,8.516700,Child,Low
755,756,1,2,"Hamalainen, Master. Viljo",M,0.67,1,1,250649,14.5000,NaN,S,7.250000,Child,Low
469,470,1,3,"Baclini, Miss. Helene Barbara",F,0.75,2,1,2666,19.2583,NaN,C,6.419433,Child,Low
644,645,1,3,"Baclini, Miss. Eugenie",F,0.75,2,1,2666,19.2583,NaN,C,6.419433,Child,Low
831,832,1,2,"Richards, Master. George Sibley",M,0.83,1,1,29106,18.7500,NaN,S,9.375000,Child,Low
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
306,307,1,1,"Fleming, Miss. Margaret",F,NaN,0,0,17421,110.8833,NaN,C,110.883300,Adult,High
334,335,1,1,"Frauenthal, Mrs. Henry William (Clara Heinshei...",F,NaN,1,0,PC 17611,133.6500,NaN,S,66.825000,Adult,High
31,32,1,1,"Spencer, Mrs. William Augustus (Marie Eugenie)",F,NaN,1,0,PC 17569,146.5208,B78,C,73.260400,Adult,High
527,528,0,1,"Farthing, Mr. John",M,NaN,0,0,PC 17483,221.7792,C95,S,221.779200,Adult,High
557,558,0,1,"Robbins, Mr. Victor",M,NaN,0,0,PC 17757,227.5250,NaN,C,227.525000,Adult,High